# Generated by Django 4.1.13 on 2024-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
