# Generated by Django 4.1.13 on 2024-05-14 21:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0002_alter_pelicula__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
